# Generated by Django 5.0.3 on 2024-03-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testWorkBack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='time_elapsed',
            field=models.CharField(default='', max_length=255),
        ),
    ]
