# Generated by Django 5.0.3 on 2024-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testWorkBack', '0002_remove_task_end_time_remove_task_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
